### ISSUE TITLE
[BUG] "curWord is null" error on startup

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1133]
Polyglot version: Windows 10 3.5

(@DraqueT moved from #1129)

Steps to reproduce:
unknown, inconsistent

![151246055-0c484aeb-f3fe-4dc2-a887-730b140b92f9.png](https://user-images.githubusercontent.com/67415128/151320118-d1dd1021-5d83-4651-90c6-b7e729836832.png)

**Comment by TrapinchO** [comment]
As for the log, I doubt I have it, since it was before I wiped all tmp files of polyglot (in context of the linked issue) (and I also do not know where the logs are)

**Comment by DraqueT** [comment]
Ooh, it's likely you still have the log. It's simply stored in the ~/PolyGlot directory along with the ini file.

**Comment by TrapinchO** [comment]
Here you go!
```
2022/01/26 21:58:06-Cannot invoke "org.darisadesigns.polyglotlina.Nodes.ConWord.getClassValues()" because "curWord" is null-java.lang.NullPointerException
java.lang.NullPointerException: Cannot invoke "org.darisadesigns.polyglotlina.Nodes.ConWord.getClassValues()" because "curWord" is null
	at org.darisadesigns.polyglotlina.polyglot@3.5/org.darisadesigns.polyglotlina.Screens.ScrLexicon.populateClassPanel(ScrLexicon.java:321)
	at org.darisadesigns.polyglotlina.polyglot@3.5/org.darisadesigns.polyglotlina.Screens.ScrLexicon.populateProperties(ScrLexicon.java:1376)
	at org.darisadesigns.polyglotlina.polyglot@3.5/org.darisadesigns.polyglotlina.Screens.ScrLexicon.lambda$updateAllValues$2(ScrLexicon.java:263)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by DraqueT** [comment]
Perfect, thank you! ^^
