### ISSUE TITLE
[BUG] UNREPRODUCED: Error: null after startup

### ISSUE THREAD

**Issue by TrapinchO** [DraqueT/PolyGlot#1202]
Polyglot version: Windows BETA from 18th May 2022 (latest as of writing this)

Context: I got this the first time opening a polyglot file after testing #1195. The test file has been removing shortly after the testing.
After opening a polyglot file and clicking "no" on both file recovery prompts without further context. The file opened (at least as far as I could tell) correctly without further problems.

Steps to reproduce:
unknown. Didn't appear after starting up again

![img](https://user-images.githubusercontent.com/67415128/183263578-c75c31bd-8fe8-4998-a48b-b5769aa8758d.png)

Error log:
```2022/08/06 19:42:42-null-java.lang.IndexOutOfBoundsException
java.lang.IndexOutOfBoundsException
	at java.base/java.io.StringWriter.write(StringWriter.java:95)
	at java.desktop/javax.swing.text.AbstractWriter.output(AbstractWriter.java:704)
	at java.desktop/javax.swing.text.html.HTMLWriter.output(HTMLWriter.java:1209)
	at java.desktop/javax.swing.text.AbstractWriter.indent(AbstractWriter.java:477)
	at java.desktop/javax.swing.text.html.HTMLWriter.indentSmart(HTMLWriter.java:1292)
	at java.desktop/javax.swing.text.html.HTMLWriter.endTag(HTMLWriter.java:602)
	at java.desktop/javax.swing.text.html.HTMLWriter.write(HTMLWriter.java:231)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Desktop.CustomControls.PHTMLEditorKit.write(PHTMLEditorKit.java:42)
	at java.desktop/javax.swing.text.JTextComponent.write(JTextComponent.java:1655)
	at java.desktop/javax.swing.JEditorPane.getText(JEditorPane.java:1507)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Desktop.CustomControls.PTextPane.isDefaultText(PTextPane.java:320)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Desktop.CustomControls.PTextPane.setText(PTextPane.java:163)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Desktop.CustomControls.PTextPane.setDefault(PTextPane.java:356)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Screens.ScrLexicon.populateProperties(ScrLexicon.java:1347)
	at org.darisadesigns.polyglotlina.polyglot@3.6/org.darisadesigns.polyglotlina.Screens.ScrLexicon.lambda$performLongRunningSetupTasks$0(ScrLexicon.java:182)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

PS: I am aware this will likely get closed since there is not enough detail for it, but I posted it in case there is a similar error in the future.

**Comment by DraqueT** [comment]
You are the best! Thank you! This one will be a cinch to fix, and I have never sen it pop in the wild, myself.
