### ISSUE TITLE
[MAC] PolyGlot freezes when opening

### ISSUE THREAD

**Issue by Khja** [DraqueT/PolyGlot#521]
When opening PG on my Mac (OS 10.11.6), the PG welcome logo appears, then it freezes and the only thing I can do is quitting or go on with another application. The name of the program is also strange: "ScrMainMenu"; is it meant to be like that?

**Comment by awkvardaardvark** [comment]
I am having the same issue. Mac OS El Capital 10.11.6, running java 9.0.1. I cannot open it with any other application (perhaps that is because I don't know/don't have any application that can run the .jar file) so my only option is to quit the application. I managed to get the information I needed from my .pgd files by downloading PG onto a family member's computer and exporting a PDF to send to myself but I am still looking for a solution that will work on my computer.

**Comment by DraqueT** [comment]
Heyo! Thanks for letting me know that you're having problems, I'll see if I can help! I'm guessing that something is going on with the startup and raising an uncaught error. Here's what to do to help track it down:

1) Click Apps->Utilities->Terminal

This will open up a terminal, which you'll use to open polyglot. 

2) Navigate in the terminal to the directory that the PolyGlot.jar file is in
If you don't know how to do this, then don't sweat it. Just open up a finder window and navigate to it there. Type 'cd ' (not including the quotes, but with a space), then  drag PolyGlot's home folder onto the terminal window. This will automatically drop in the directory. Just hit enter after and you'll be in the right spot. If this part gives you trouble, let me know and I can help.

3) In the terminal, type 'Java -jar PolyGlot.jar' and hit enter. This should make the program attempt to start up. 

4) Whatever text appears in the terminal, please copy/paste into a replyl. 

if you run into trouble please let me know and I'll try and help you out! :3

**Comment by Khja** [comment]
Hey! Thanks for your help! I will try it out and then I will eventually let you know if I run into trouble.

**Comment by maxx-towers** [comment]
I tried doing the Apps->Utilities->Terminal solution that sent Khja, but It didn't work for me...I don't really know what I'm doing with java (or any scripts for that matter--newbie here). Here's what the script looked like:

Last login: Wed Jan  3 08:05:35 on console
Maxs-MBP:~ maxtowers$ cd/Users/maxtowers/Desktop/PolyGlot 
-bash: cd/Users/maxtowers/Desktop/PolyGlot: No such file or directory
Maxs-MBP:~ maxtowers$ Java -jar PolyGlot.jar
Error: Unable to access jarfile PolyGlot.jar
Maxs-MBP:~ maxtowers$ cd/Users/maxtowers/Desktop/PolyGlot/PolyGlot.jar 
-bash: cd/Users/maxtowers/Desktop/PolyGlot/PolyGlot.jar: No such file or directory
Maxs-MBP:~ maxtowers$ cd/Users/maxtowers/Desktop/DraqueT-PolyGlot-4f7d4be\ 2 
-bash: cd/Users/maxtowers/Desktop/DraqueT-PolyGlot-4f7d4be 2: No such file or directory
Maxs-MBP:~ maxtowers$ cd /Users/maxtowers/Desktop/PolyGlot 
Maxs-MBP:PolyGlot maxtowers$ Java -jar PolyGlot.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.simplericity.macify.eawt.DefaultApplication (file:/Users/maxtowers/Desktop/PolyGlot/lib/macify-1.6.jar) to method com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of org.simplericity.macify.eawt.DefaultApplication
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.lang.NoSuchMethodException: com.apple.eawt.Application.addApplicationListener(com.apple.eawt.ApplicationListener)
	at org.simplericity.macify.eawt.DefaultApplication.callMethod(DefaultApplication.java:380)
	at org.simplericity.macify.eawt.DefaultApplication.addApplicationListener(DefaultApplication.java:102)
	at PolyGlot.Screens.ScrMainMenu.activateMacify(ScrMainMenu.java:157)
	at PolyGlot.Screens.ScrMainMenu.<init>(ScrMainMenu.java:113)
	at PolyGlot.Screens.ScrMainMenu$30.run(ScrMainMenu.java:1337)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchMethodException: com.apple.eawt.Application.addApplicationListener(com.apple.eawt.ApplicationListener)
	at java.base/java.lang.Class.getMethod(Class.java:2065)
	at org.simplericity.macify.eawt.DefaultApplication.callMethod(DefaultApplication.java:377)
	... 18 more
Maxs-MBP:PolyGlot maxtowers$ Java 

Some help would be greatly appreciated

**Comment by DraqueT** [comment]
Thank you! That tells me exactly what the problem is and how to fix it!
I'll update here once the issue is resolved, and you can have a beta
version of PolyGlot that corrects the problem if you like. :3

- Draque

**Comment by DraqueT** [comment]
Heyo! This is complete now. If you're interested in a beta copy in which this is corrected, toss me an email! ^^

**Comment by Khja** [comment]
Hey! When I type in the code into the terminal, PolyGlot opens up (only the logo, as before) and then the terminal says this:

freds-macbook-2:PolyGlot Macbook$ cd /Users/Macbook/Downloads/
PolyGlot
freds-macbook-2:PolyGlot Macbook$ Java -jar PolyGlot.jar
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by
org.simplericity.macify.eawt.DefaultApplication (file:/Users/
Macbook/Downloads/PolyGlot/lib/macify-1.6.jar) to method
com.apple.eawt.Application.getApplication()
WARNING: Please consider reporting this to the maintainers of
org.simplericity.macify.eawt.DefaultApplication
WARNING: Use --illegal-access=warn to enable warnings of further
illegal reflective access operations
WARNING: All illegal access operations will be denied in a future
release
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException:
java.lang.NoSuchMethodException:
com.apple.eawt.Application.addApplicationListener(com.apple.eawt.App
licationListener)
    at
org.simplericity.macify.eawt.DefaultApplication.callMethod(DefaultAp
plication.java:380)
    at
org.simplericity.macify.eawt.DefaultApplication.addApplicationListen
er(DefaultApplication.java:102)
    at
PolyGlot.Screens.ScrMainMenu.activateMacify(ScrMainMenu.java:157)
    at PolyGlot.Screens.ScrMainMenu.<init>(ScrMainMenu.java:113)
    at PolyGlot.Screens.ScrMainMenu$30.run(ScrMainMenu.java:1337)
    at java.desktop/
java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
    at java.desktop/
java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
    at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:
97)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
    at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
    at java.base/java.security.AccessController.doPrivileged(Native
Method)
    at java.base/java.security.ProtectionDomain
$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.jav
a:89)
    at java.desktop/
java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
    at java.desktop/
java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThr
ead.java:199)
    at java.desktop/
java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread
.java:124)
    at java.desktop/
java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThr
ead.java:113)
    at java.desktop/
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
    at java.desktop/
java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:
101)
    at java.desktop/
java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.NoSuchMethodException:
com.apple.eawt.Application.addApplicationListener(com.apple.eawt.App
licationListener)
    at java.base/java.lang.Class.getMethod(Class.java:2065)
    at
org.simplericity.macify.eawt.DefaultApplication.callMethod(DefaultAp
plication.java:377)
... 18 more 

I hope it helps, even though Maxx has already replied to your email. 

Khja

Il giorno 5 gen 2018, alle ore 00:24, maxx-towers <notifications@github.com> ha scritto:

**Comment by DraqueT** [comment]
Yep, this is a bug that has now been fixed! If you would like me to email
you a beta version in which this no longer occurs, please let me know where
to send it here. ^^

- Draque

**Comment by awkvardaardvark** [comment]
Hey there,

I received similar results when I followed the steps in the Terminal (got a warning about illegal reflective access). Was wondering if I could try the beta version as well, please let me know where I can send you my email address

Thanks so much for your help!

**Comment by DraqueT** [comment]
I'm actually hoping to release v 2.2 tonight, so it won't be much of a wait
for you to get the real version. ^^

- Draque

**Comment by awkvardaardvark** [comment]
Ah ok I see. Thank you! :)

**Comment by wleightond** [comment]
Hi DraqueT,

I'm having a similar issue on Sierra, even on version 2.2. The error is different though:

```
user@mymac:~/Downloads/PolyGlot$ Java -jar PolyGlot.jar 
libpng warning: iCCP: known incorrect sRGB profile
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$5.invalidated(Text.java:501)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.bind(ObjectPropertyBase.java:174)
	at javafx.css.StyleableObjectProperty.bind(StyleableObjectProperty.java:75)
	at com.sun.javafx.scene.control.skin.LabeledText.<init>(LabeledText.java:82)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.<init>(LabeledSkinBase.java:125)
	at com.sun.javafx.scene.control.skin.LabelSkin.<init>(LabelSkin.java:39)
	at javafx.scene.control.Label.createDefaultSkin(Label.java:158)
	at javafx.scene.control.Control.impl_processCSS(Control.java:859)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:862)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9056)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at com.sun.javafx.stage.EmbeddedWindow.show(EmbeddedWindow.java:58)
	at javafx.embed.swing.JFXPanel.setSceneImpl(JFXPanel.java:299)
	at javafx.embed.swing.JFXPanel.setScene(JFXPanel.java:269)
	at PolyGlot.Screens.ScrLexicon.initFX(ScrLexicon.java:581)
	at PolyGlot.Screens.ScrLexicon.access$1900(ScrLexicon.java:108)
	at PolyGlot.Screens.ScrLexicon$7.run(ScrLexicon.java:563)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
```
