### ISSUE TITLE
Won't open on Ubuntu 18.04

### ISSUE THREAD

**Issue by chickenfilter** [DraqueT/PolyGlot#559]
Displays logo, and then quits immediately. When run from the terminal, it gives the following error message:
`libpng warning: iCCP: known incorrect sRGB profile
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: javafx/embed/swing/JFXPanel
	at PolyGlot.Screens.ScrMainMenu.<init>(ScrMainMenu.java:89)
	at PolyGlot.Screens.ScrMainMenu$30.run(ScrMainMenu.java:1386)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: javafx.embed.swing.JFXPanel
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 16 more`
I am sure that i have got the latest OpenJDK and OpenJFX installed, so I am confused as to why this is happening.

**Comment by DraqueT** [comment]
What version of Java are you running currently? PolyGlot should be checking for that at startup, but I know there can be some weirdness if users are still on J7 or lower.

Thanks for taking the time to write up a ticket here! I'll def try to get this working for you. ^^

**Comment by DraqueT** [comment]
Heyo! Coincidentally, another user had the same issue recently. You can correct it by running the following in your console to update open JFX:

sudo dnf install java-1.8.0-openjdk-openjfx

Please let me know if this corrects the problem!

**Comment by chickenfilter** [comment]
i have Java 10, which is the default in Ubuntu 18.04. I tried to run the command you gave me, but I don't think that the dnf package manager is available on Ubuntu. Even so, my openJFX is already at the latest version available from the repos (8u161-b12-1ubuntu2, if it helps.).

**Comment by DraqueT** [comment]
I am closing this for now, but may reopen depending on relevant updates to Ubuntu.
