### ISSUE TITLE
Update Fedora install instructions

### ISSUE THREAD

**Issue by MixedMatched** [DraqueT/PolyGlot#560]
User experienced problems outlined in original text. Fixed via install of alt JFX package:
sudo dnf install java-1.8.0-openjdk-openjfx

ORIGINAL USER TEXT:
Output of `java - jar PolyGlot.jar` is:
`libpng warning: iCCP: known incorrect sRGB profile
Graphics Device initialization failed for :  es2, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:280)
	at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:221)
	at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:205)
	at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:209)
	at javafx.embed.swing.JFXPanel.initFx(JFXPanel.java:215)
	at javafx.embed.swing.JFXPanel.<init>(JFXPanel.java:230)
	at PolyGlot.Screens.ScrLexicon.<init>(ScrLexicon.java:147)
	at PolyGlot.Screens.ScrLexicon.run(ScrLexicon.java:1516)
	at PolyGlot.Screens.ScrMainMenu.<init>(ScrMainMenu.java:89)
	at PolyGlot.Screens.ScrMainMenu$30.run(ScrMainMenu.java:1386)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:94)
	at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:124)
	at java.lang.Thread.run(Thread.java:748)`

Latest version of OpenJDK and OpenJFX. Output of `java -version` is:
`openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)`

**Comment by MixedMatched** [comment]
Had to install alternate version of openJDK/openJFK. Just used: 
`sudo dnf install java-1.8.0-openjdk-openjfx`

**Comment by DraqueT** [comment]
Thanks for taking the time to write this up, either way! I'm going to go ahead and update the manual with this info for people who might run into it in the future. ^^
