### ISSUE TITLE
Doesn't work in OSX with JDK 12

### ISSUE THREAD

**Issue by Xe** [DraqueT/PolyGlot#747]
I get the loading screen for a few seconds and then this:

```
chrysalis:PolyGlot within$ java -jar PolyGlot.jar
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/AboutHandler
	at PolyGlot.PolyGlot.main(PolyGlot.java:54)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.AboutHandler
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

**Comment by DraqueT** [comment]
Thanks for the heads up! For the moment, I would recommend using Java 8 for Polyglot. At the moment, I am working hard to convert the application to pure Java 12 so that it can be distributed as an executable image rather than a jar. 

So for future versions, none of the question of local Java will come up at all.

**Comment by DraqueT** [comment]
Closing due to #730 being completed. PolyGlot has been upgraded to java 12.

**Comment by Xe** [comment]
Thanks so much!

**Comment by DraqueT** [comment]
If you would like a preview copy of PolyGlot 3.0 (still very much in Alpha) that is 100% Java 12, please let me know and I will hook you up! ^^
