### ISSUE TITLE
Recursing Etymologies cause print of etymology trees to crash PolyGlot

### ISSUE THREAD

**Issue by brunoczim** [DraqueT/PolyGlot#890]
UPDATED TEXT:
If there are loops in etymological logic (a word leading to itself in its own history), the print print etymology option in print to PDF will cause PolyGlot to crash. 

It is possible this was fixed by switching from a thrown error to a warning, but double check that the printing of the etymology screen itself doesn't cause an unhandled exception when printing in the J8 module. 

ORIGINAL TEXT:
At least it does in my conlang. [You can download it to test here](https://github.com/brunoczim/ficlangs/blob/20da5adfbcc432bfcbe2e20240e28dd9127cf957/Star%20Folk.pgd).

**Comment by DraqueT** [comment]
Could you please email me the language file causing this and the error log from PolyGlot? The errorlog can be found in your user folder under the PolyGlot directory. My email is draquemail@gmail.com

Thank you for reporting this bug! User response is a massive help in bug tracking!

**Comment by DraqueT** [comment]
Heyo! As a heads up, I downloaded your language from your other ticket and it is super cool! I love the look of your script and I love how much care you're taking with the etymology/root of words! The next version of PolyGlot is going to have evolution options that I think you might really dig...

Anyhow. I have not been able to reproduce the issue you describe with the file. If you can get the error log to me, it will let me see a lot more about exactly what's going on and what difference between our systems is making it happen for you. In the mean time, let me know if you would like me to just email you a copy of the pdf that printed out.

**Comment by brunoczim** [comment]
I am running on Arch Linux, if this helps.

**Comment by brunoczim** [comment]
How do I access the error log?

**Comment by brunoczim** [comment]
Nevermind, I found out. Here it is:

```
java.version : 14
java.vendor : Oracle Corporation
java.vendor.url : https://java.oracle.com/
java.vm.specification.version : 14
java.vm.specification.name : Java Virtual Machine Specification
java.vm.version : 14+36-1461
java.vm.vendor : Oracle Corporation
java.vm.name : OpenJDK 64-Bit Server VM
java.specification.version : 14
java.specification.vendor : Oracle Corporation
java.specification.name : Java Platform API Specification
java.class.version : 58.0
java.ext.dirs : null
os.name : Linux
os.arch : amd64
os.version : 5.6.8-arch1-1

2020/05/02 21:55:10-Unable to print to PDF: ERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorSUCCESS-java.io.IOException
java.io.IOException: Unable to print to PDF: ERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorERROR: Etymology Rendering ErrorSUCCESS
	at org.darisadesigns.polyglotlina.polyglot@3.1.3/org.darisadesigns.polyglotlina.Java8Bridge.exportPdf(Java8Bridge.java:98)
	at org.darisadesigns.polyglotlina.polyglot@3.1.3/org.darisadesigns.polyglotlina.Screens.ScrPrintToPDF.btnPrintActionPerformed(ScrPrintToPDF.java:342)
	at org.darisadesigns.polyglotlina.polyglot@3.1.3/org.darisadesigns.polyglotlina.Screens.ScrPrintToPDF$3.actionPerformed(ScrPrintToPDF.java:271)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/java.awt.Component.show(Component.java:1717)
	at java.desktop/java.awt.Component.setVisible(Component.java:1664)
	at java.desktop/java.awt.Window.setVisible(Window.java:1023)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.darisadesigns.polyglotlina.polyglot@3.1.3/org.darisadesigns.polyglotlina.CustomControls.PDialog.setVisible(PDialog.java:195)
	at org.darisadesigns.polyglotlina.polyglot@3.1.3/org.darisadesigns.polyglotlina.Screens.ScrPrintToPDF.lambda$run$0(ScrPrintToPDF.java:402)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

This time it exited with an error instead of freezing

**Comment by DraqueT** [comment]
Thank you for finding that! I'm spinning up my Linux virtual right now to investigate, and that will help a lot.

**Comment by DraqueT** [comment]
What's the exact distro/UI of Arch that you're using? Still have not been able to isolate this bug, although I'm still digging.

**Comment by brunoczim** [comment]
It's i3. Maybe we should try something else. I had to install PolyGlot manually, cause .deb is only for debian based. I might have missed some dependency. Are there any system-level dependencies?

**Comment by DraqueT** [comment]
Ahhh, that might be your issue. I was just running things from within a dev environment and didn't even consider the installation.

Anyhow, here is one thing that might be the issue:
Print to PDF is actually stuck back in Java 8 land because it uses iText (and who knows when they'll come up past J9). Here's where the exception is happening:

https://github.com/DraqueT/PolyGlotPDF/blob/master/src/PolyGlot/CustomControls/PPanelDrawEtymology.java#L368

If you want to messing with the ultra bare bones J8 printing core, you can download it from the link below this. If you unzip, you'll find a Java 8 program that can be run and which has a very basic UI. I've used this for debugging in the past. You might have more luck with that.

**Comment by DraqueT** [comment]
Might have helped if I had included the last link. XD

https://github.com/DraqueT/PolyGlot/blob/master/assets/assets/org/DarisaDesigns/java_8_bridge.zip

**Comment by DraqueT** [comment]
I know this is a bit late, but I think I've found the issue. Recursive etymologies can create this bug. They SHOULD be prohibited at the time of creation, but I must have missed something.
